### ISSUE TITLE
Orientation sensitivity

### ISSUE THREAD

**Issue by bandtank** [rorodriguez116/SwiftCamera#1]
Thanks for writing this awesome camera. Being able to customize a camera interface is exactly what I need, so this is perfect.

I have a question about orientation. it looks like the camera ignores orientation, which is fine for my purposes, but I'm not sure if I'm right. Is there anything in the code that handles orientation or does it need to be added?

**Comment by rorodriguez116** [comment]
Hey, thank you for using this library. Currently there's no support for orientation changes in the UI, only portrait orientation is supported.
